---
- name: install sysstat
  hosts: hos3
  vars:
    sysstat_default_file: |
      #
      # Default settings for /etc/init.d/sysstat, /etc/cron.d/sysstat
      # and /etc/cron.daily/sysstat files
      #

      # Should sadc collect system activity informations? Valid values
      # are "true" and "false". Please do not put other values, they
      # will be overwritten by debconf!
      ENABLED="true"
    sysstat_crond_file: |
      # The first element of the path is a directory where the debian-sa1
      # script is located
      PATH=/usr/lib/sysstat:/usr/sbin:/usr/sbin:/usr/bin:/sbin:/bin

      # Activity reports every 10 minutes everyday
      */1 * * * * root command -v debian-sa1 > /dev/null && debian-sa1 1 1

      # Additional run at 23:59 to rotate the statistics file
      59 23 * * * root command -v debian-sa1 > /dev/null && debian-sa1 60 2

  tasks:
    - name: unexpected os distribution
      debug:
        msg: os distribution {{ ansible_os_family }} is not support
      when: not ansible_os_family == "Debian"

    - name: apt
      apt:
        name: sysstat
        state: present
      become: true

    - name: set up the sysstat
      copy:
        dest: /etc/default/sysstat
        content: '{{ sysstat_default_file }}'
      become: true

    - name: set the crolling interval
      copy:
        dest: /etc/cron.d/sysstat
        content: '{{ sysstat_crond_file }}'
      become: true
