---
- name: install prerequirement package
  apt:
    name: "{{ item }}"
  with_items:
    - "{{ debian_packages }}"
  when: ansible_distribution == 'Debian'

- name: download install script
  get_url:
    url: https://my-netdata.io/kickstart.sh
    dest: /root/netdata.sh
    mode: 0700

- command: which netdata
  register: which_result
  ignore_errors: yes

- name: install netdata
  command: bash /root/netdata.sh --non-interactive
  register: bash_result
  when: which_result.rc != 0

- name: config NetData
  template:
    src: netdata.conf.j2
    dest: /etc/netdata/netdata.conf
    owner: netdata
    group: root
    backup: yes
  notify: restart netdata
