---
# Enable apt repository via internet
- include: ../../debian-repository/tasks/turn-on.yml
  when: ansible_distribution == 'Debian'

# Install netdata
- include: install.yml
- include: config.yml
  when: "inventory_hostname == 'cont1' or 'cont' in group_names"

# Disable apt repository
- include: ../../debian-repository/tasks/turn-off.yml
  when: ansible_distribution == 'Debian'
