---
- name: remove a useless account
  user:
    name: "{{ item }}"
    state: absent
  with_items:
    - ip
    - uucp

- name: set permission an account file
  file:
    path: "{{ item }}"
    mode: 644
  with_items:
    - /etc/passwd
    - /etc/group

- name: set permission a shadow file
  file:
    path: /etc/shadow
    mode: 400

- name: change password policy file
  template:
    src: login.defs.j2
    dest: /etc/login.defs
    owner: root
    group: root
    mode: 644

- name: add a wheel group
  group:
    name: wheel

- name: allow su command of wheel group
  file:
    path: /bin/su
    mode: 4750
    group: wheel

- name: add stack user in wheel
  user:
    name: stack
    groups: wheel
    append: yes

- name: remove suid and sgid in user password file
  file:
    path: "{{ item }}"
    mode: "a-s"
    follow: yes
  with_items:
    - /sbin/unix_chkpwd
    - /usr/bin/newgrp

- name: disable service that related with r
  file:
    path: "{{ item }}"
    mode: 000
    owner: root
    group: root
    state: touch
  with_items:
    - /etc/hosts.equiv
    - /root/.rhosts
    - /home/stack/.rhosts

- name: set timeout that ssh session
  lineinfile:
    dest: /etc/bash.bashrc
    line: 'TMOUT=3600'
    backup: yes

- name: access deny that root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin without-password'
    backup: yes

- name: set permission a system log
  file:
    name: /etc/login.defs
    mode: 640

- name: store cycle a system log
  lineinfile:
    dest: "{{ item }}"
    regexp: '^rotate'
    line: 'rotate 15'
    backup: yes
  with_items:
    - /etc/logrotate.conf
    - /etc/logrotate.d/rsyslog

- name: set a rsyslog
  lineinfile:
    dest: /etc/rsyslog.conf
    line: "{{ item }}"
    mode: 640
    backup: yes
  with_items:
    - '*.notice        /var/log/messages'
    - '*.alert         /dev/console'
    - '*.emerg         *'
