---
- name: remove the default account
  user:
    name: "{{ item }}"
    state: absent
  with_items:
    - ip
    - uucp

- name: set a file permission
  file:
    path: "{{ item }}"
    mode: 644
  with_items:
    - /etc/passwd
    - /etc/group

- name: set a file permission on /etc/shadow
  file:
    path: /etc/shadow
    mode: 400

- name: password policy
  template:
    src: login.defs.j2
    dest: /etc/login.defs
    owner: root
    group: root
    mode: 644

- name: adding the wheel group
  group:
    name: wheel

- name: allow su command of wheel group
  file:
    path: /bin/su
    mode: 4750
    group: wheel

- name: adding the wheel group in stack user
  user:
    name: stack
    groups: wheel
    append: yes

- name: remove suid, sgid from file
  file:
    path: "{{ item }}"
    mode: "a-s"
    follow: yes
  with_items:
    - /sbin/unix_chkpwd
    - /usr/bin/newgrp

- name: remove r service
  file:
    path: "{{ item }}"
    mode: 000
    owner: root
    group: root
    state: touch
  with_items:
    - /etc/hosts.equiv
    - /root/.rhosts
    - /home/stack/.rhosts

- name: setting a session timeout
  lineinfile:
    dest: /etc/bash.bashrc
    line: 'TMOUT=3600'
    backup: yes

- name: access deny a telnet and ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin without-password'
    backup: yes

- name: setting a system log
  file:
    name: /etc/login.defs
    mode: 640

- name: store of system log
  lineinfile:
    dest: "{{ item }}"
    regexp: '^rotate'
    line: 'rotate 15'
    backup: yes
  with_items:
    - /etc/logrotate.conf
    - /etc/logrotate.d/rsyslog

- name: enable of system log
  lineinfile:
    dest: /etc/rsyslog.conf
    line: "{{ item }}"
    mode: 640
    backup: yes
  with_items:
    - '*.notice        /var/log/messages'
    - '*.alert         /dev/console'
    - '*.emerg         *'
