---
RABBITMQ_USER: sysop
RABBITMQ_PASS: sysop
MYSQL_USER: sysop
MYSQL_PASS: sysop

netdata_config_file: /etc/netdata/netdata.conf

# with Debian
debian_packages:
  - zlib1g-dev
  - uuid-dev
  - libmnl-dev
  - gcc
  - make
  - git
  - autoconf
  - autoconf-archive
  - autogen
  - automake
  - pkg-config
  - curl
